### ISSUE TITLE
Unable to construct a `Config` with just a single `ConfigSource`, no default/discovered.

### ISSUE THREAD

**Issue by jkschneider** [microbean/microbean-microprofile-config#1]
This fails to add any config sources to the constructed `Config` because of [this](https://github.com/microbean/microbean-microprofile-config/blob/master/src/main/java/org/microbean/microprofile/config/ConfigBuilder.java#L105) (i.e. sources is null when we choose not to add default or discovered config sources).

```java
ConfigProviderResolver.instance()
                .getBuilder()
                .withSources(new MyCustomSource())
                .build()
```

**Comment by ljnelson** [comment]
Thanks for the report; will definitely look into this.  Probably this case should be in the MicroProfile Config TCK as well.

**Comment by jkschneider** [comment]
Thanks. I thought the same, should definitely be in the TCK.

**Comment by ljnelson** [comment]
Note to self: reverse the following loops/blocks:

https://github.com/microbean/microbean-microprofile-config/blob/096a9aec98045c4efadde360803668d9b69352ad/src/main/java/org/microbean/microprofile/config/ConfigBuilder.java#L105-L110

**Comment by ljnelson** [comment]
@jkschneider  See if #2 fixes this for you.

**Comment by jkschneider** [comment]
@ljnelson Added a review comment, but yes this would fix the issue.
